version: '3'

services:
  db:
    image: mongo:5.0.8
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=nmCJ5L8bYiz34vZFFi191
